stages:
  - build
  - deploy

variables:
  IMAGE_NAME: "fastapi:latest"
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

build:
  stage: build
  image: docker:latest
  services:
    - name: docker:dind
      alias: docker
  script:
    - echo "Checking DNS resolution for 'docker'..."
    - nslookup docker  # Check if "docker" resolves to an IP address
    - ping -c 4 docker  # Ping the "docker" hostname to verify connectivity
    - echo "Checking Docker daemon..."
    - docker info
    - echo "Building Docker image with docker-compose..."
    - docker-compose build
    - docker tag fastapi:latest $IMAGE_NAME

deploy:
  stage: deploy
  image: docker:latest
  services:
    - name: docker:dind
      alias: docker
  script:
    - echo "Deploying with docker-compose..."
    - docker-compose pull
    - docker-compose up -d