deploy_to_server:
  stage: deploy
  image: ruby:2.7
  script:
    # Setup SSH
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    # Write key from GitLab variable
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa

    # Convert to PEM if needed
    - echo "Converting key to PEM format..."
    - mv ~/.ssh/id_rsa ~/.ssh/id_rsa_openssh
    - ssh-keygen -p -m PEM -f ~/.ssh/id_rsa_openssh -N "" -q || { echo "Key conversion failed"; exit 1; }
    - mv ~/.ssh/id_rsa_openssh ~/.ssh/id_rsa

    # Test SSH connection
    - echo "Testing SSH connection to remote server..."
    - ssh -o StrictHostKeyChecking=no -p 9022 shuvechhya@10.10.40.114 "echo 'SSH OK'"

        # Run docker-compose commands on server after git pull
    - echo "Pulling latest changes and restarting Docker Compose project..."
    - ssh -T -o StrictHostKeyChecking=no -p 9022 shuvechhya@10.10.40.114 "
        cd /home/shuvechhya/ssl/SSL_new &&
        git config --global --add safe.directory /home/shuvechhya/ssl/SSL_new &&
        git pull https://shuvechhya:<token>@git.accessworld.net/shuvechhya/SSL_new.git main &&
        docker-compose down &&
        docker-compose up -d
      "


  tags:
    - shuvechhya
  only:
    - main
