stages:
  - build
  - deploy

variables:
  CI_REGISTRY: "gitlab.example.com:5050"
  CI_PROJECT_NAMESPACE: "$CI_PROJECT_NAMESPACE"
  CI_PROJECT_NAME: "$CI_PROJECT_NAME"
  IMAGE_NAME: "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/fastapi:latest"

build:
  stage: build
  image: docker:latest
  services:
    - name: docker:dind
      alias: docker  # Ensures the `docker` hostname can be resolved
  script:
    - echo "Building Docker image with docker-compose..."
    - docker-compose build
    - docker tag fastapi:latest $IMAGE_NAME
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker push $IMAGE_NAME

deploy:
  stage: deploy
  image: docker:latest
  services:
    - name: docker:dind
      alias: docker  # Ensures the `docker` hostname can be resolved
  script:
    - echo "Deploying with docker-compose..."
    - docker-compose pull
    - docker-compose up -d
